# Exported from Render
version: "1"
services:
  # Frontend Service
  - type: web
    name: setharkk-frontend
    runtime: node
    repo: https://github.com/Setharkk/Application-Setharkk
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend && npm run preview -- --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VITE_API_URL
        value: https://setharkk-backend.onrender.com/api

  # Backend Service
  - type: web
    name: setharkk-backend
    runtime: node
    repo: https://github.com/Setharkk/Application-Setharkk
    buildCommand: cd backend && npm ci
    startCommand: cd backend && node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URI
        sync: false
      - key: POSTGRES_URI
        sync: false

  # Nginx Service
  - type: web
    name: setharkk-nginx
    runtime: docker
    repo: https://github.com/Setharkk/Application-Setharkk
    dockerContext: ./nginx
    dockerfilePath: ./nginx/Dockerfile
    plan: free
    envVars:
      - key: FRONTEND_URL
        fromService:
          name: setharkk-frontend
          type: web
          property: url
      - key: BACKEND_URL
        fromService:
          name: setharkk-backend
          type: web
          property: url
    healthCheckPath: /health 
