# Blueprint configuration for Setharkk application
# This includes a frontend service, a backend service, and the databases (PostgreSQL, MongoDB, Redis).

services:
  # Frontend Service
  - type: web
    name: setharkk-frontend
    plan: free
    runtime: docker
    repo: https://github.com/Setharkk/Application-Setharkk
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: VITE_API_URL
        fromService:
          name: setharkk-backend
          type: web
          property: url

  # Backend Service
  - type: web
    name: setharkk-backend
    plan: free
    runtime: docker
    repo: https://github.com/Setharkk/Application-Setharkk
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: POSTGRES_URI
        fromDatabase:
          name: setharkk-postgres
          property: connectionString
      - key: MONGODB_URI
        fromDatabase:
          name: setharkk-mongodb
          property: connectionString
      - key: REDIS_URI
        fromDatabase:
          name: setharkk-redis
          property: connectionString

databases:
  # PostgreSQL Database
  - name: setharkk-postgres
    plan: free

  # MongoDB Database
  - name: setharkk-mongodb
    plan: free

  # Redis Cache
  - name: setharkk-redis
    plan: free
