services:
- type: web
  name: Application-Setharkk
  runtime: docker
  repo: https://github.com/Setharkk/Application-Setharkk
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"

