# Exported from Render on 2025-01-13T14:17:12Z
services:
- type: web
  name: Application-Setharkk
  runtime: docker
  repo: https://github.com/Setharkk/Application-Setharkk
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
