# Blueprint configuration for Setharkk application
# This includes a frontend service, a backend service, and the databases (PostgreSQL, MongoDB, Redis).
# Blueprint configuration for Setharkk application
# This includes a frontend service, a backend service, and the databases (PostgreSQL, MongoDB, Redis).

services:
  # Frontend Service
  - type: web
    name: setharkk-frontend
    runtime: node
    repo: https://github.com/Setharkk/Application-Setharkk
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://setharkk-backend.onrender.com/api

  # Backend Service
  - type: web
    name: setharkk-backend
    runtime: node
    repo: https://github.com/Setharkk/Application-Setharkk
    rootDirectory: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        fromDatabase:
          name: setharkk-mongodb
          property: connectionString
      - key: REDIS_URI
        fromDatabase:
          name: setharkk-redis
          property: connectionString
      - key: POSTGRES_URI
        fromDatabase:
          name: setharkk-postgres
          property: connectionString

databases:
  # PostgreSQL Database
  - name: setharkk-postgres
    plan: free

  # MongoDB Database
  - name: setharkk-mongodb
    plan: free

  # Redis Cache
  - name: setharkk-redis
    plan: free

